USE QuanLyGiatUi
GO

CREATE TABLE Services (
	STT INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Price MONEY NOT NULL CHECK (Price > 0)
)
Go
SELECT * FROM Services

CREATE TABLE Orders (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CustomerName NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(20),
	[Address] NVARCHAR(200),
	OrderName NVARCHAR(100),
	[Service] NVARCHAR(50) NOT NULL,
	[Weight] FLOAT NOT NULL,
	Delivery BIT NOT NULL,
	Price DECIMAL(18,0) NOT NULL,
	[Status] NVARCHAR(100) NOT NULL,
	[Date] DATETIME NOT NULL DEFAULT GETDATE()
)
SELECT * FROM Orders
GO

CREATE TABLE Staff (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(200),
	Phone NVARCHAR(20) NOT NULL,
	[Function] NVARCHAR(100) NOT NULL
)
GO

INSERT INTO Staff VALUES (N'Sang', N'NVC', '0125487', N'Nhân viên tiếp nhận')
GO
SELECT * FROM Staff

SELECT SUM(Price) FROM Orders WHERE Status = N'Đã thanh toán' AND Day(Date) = 28
SELECT * FROM Orders WHERE MONTH(Date) = 10